#pragma once

// 在构建EPP时，大量作为判断的宏是由外部构建工具定义的，在这里进行转换

// EPP逻辑标志
#define EPP_FALSE				0
#define EPP_TRUE				1

// 编译器相关宏
#define EPP_COMPILER_GCC		0
#define EPP_COMPILER_CLANG		1
#define EPP_COMPILER_MSVC		2
#define EPP_COMPILER_ICC		3
#define EPP_COMPILER_TCC		4



#ifdef EPP_BUILD_COMPILER_GCC
	#define EPP_CURRENT_COMPILER	EPP_COMPILER_GCC
#endif

#ifdef EPP_BUILD_COMPILER_CLANG
	#define EPP_CURRENT_COMPILER	EPP_COMPILER_CLANG
#endif

#ifdef EPP_BUILD_COMPILER_MSVC
	#define EPP_CURRENT_COMPILER	EPP_COMPILER_MSVC
#endif

#ifdef EPP_BUILD_COMPILER_ICC
	#define EPP_CURRENT_COMPILER	EPP_COMPILER_ICC
#endif

#ifdef EPP_BUILD_COMPILER_TCC
	#define EPP_CURRENT_COMPILER	EPP_COMPILER_TCC
#endif



// 架构相关宏
#define EPP_ARCH_AARCH64		0
#define EPP_ARCH_ALPHA			1
#define EPP_ARCH_ARM			2
#define EPP_ARCH_AVR			3
#define EPP_ARCH_CRIS			4
#define EPP_ARCH_HPPA			5
#define EPP_ARCH_I386			6
#define EPP_ARCH_LOONGARCH64	7
#define EPP_ARCH_M68K			8
#define EPP_ARCH_MICROBLAZE		9
#define EPP_ARCH_MICROBLAZEEL	10
#define EPP_ARCH_MIPS			11
#define EPP_ARCH_MIPS64			12
#define EPP_ARCH_MIPS64EL		13
#define EPP_ARCH_MIPSEL			14
#define EPP_ARCH_NIOS2			15
#define EPP_ARCH_OR1K			16
#define EPP_ARCH_PPC			17
#define EPP_ARCH_PPC64			18
#define EPP_ARCH_RISCV32		19
#define EPP_ARCH_RISCV64		20
#define EPP_ARCH_RX				21
#define EPP_ARCH_S390X			22
#define EPP_ARCH_SH4			23
#define EPP_ARCH_SH4EB			24
#define EPP_ARCH_SPARC			25
#define EPP_ARCH_SPARC64		26
#define EPP_ARCH_TRICORE		27
#define EPP_ARCH_X86_64			28
#define EPP_ARCH_XTENSA			29
#define EPP_ARCH_XTENSAEB		30


// 宏转换
#ifdef EPP_TARGET_ARCH_AARCH64
	#define EPP_CURRENT_ARCH	EPP_ARCH_AARCH64
#endif

#ifdef EPP_TARGET_ARCH_ALPHA
	#define EPP_CURRENT_ARCH	EPP_ARCH_ALPHA
#endif

#ifdef EPP_TARGET_ARCH_ARM
	#define EPP_CURRENT_ARCH	EPP_ARCH_ARM
#endif

#ifdef EPP_TARGET_ARCH_AVR
	#define EPP_CURRENT_ARCH	EPP_ARCH_AVR
#endif

#ifdef EPP_TARGET_ARCH_CRIS
	#define EPP_CURRENT_ARCH	EPP_ARCH_CRIS
#endif

#ifdef EPP_TARGET_ARCH_HPPA
	#define EPP_CURRENT_ARCH	EPP_ARCH_HPPA
#endif

#ifdef EPP_TARGET_ARCH_I386
	#define EPP_CURRENT_ARCH	EPP_ARCH_I386
#endif

#ifdef EPP_TARGET_ARCH_LOONGARCH64
	#define EPP_CURRENT_ARCH	EPP_ARCH_LOONGARCH64
#endif

#ifdef EPP_TARGET_ARCH_M68K
	#define EPP_CURRENT_ARCH	EPP_ARCH_M68K
#endif

#ifdef EPP_TARGET_ARCH_MICROBLAZE
	#define EPP_CURRENT_ARCH	EPP_ARCH_MICROBLAZE
#endif

#ifdef EPP_TARGET_ARCH_MICROBLAZEEL
	#define EPP_CURRENT_ARCH	EPP_ARCH_MICROBLAZEEL
#endif

#ifdef EPP_TARGET_ARCH_MIPS
	#define EPP_CURRENT_ARCH	EPP_ARCH_MIPS
#endif

#ifdef EPP_TARGET_ARCH_MIPS64
	#define EPP_CURRENT_ARCH	EPP_ARCH_MIPS64
#endif

#ifdef EPP_TARGET_ARCH_MIPS64EL
	#define EPP_CURRENT_ARCH	EPP_ARCH_MIPS64EL
#endif

#ifdef EPP_TARGET_ARCH_MIPSEL
	#define EPP_CURRENT_ARCH	EPP_ARCH_MIPSEL
#endif

#ifdef EPP_TARGET_ARCH_NIOS2
	#define EPP_CURRENT_ARCH	EPP_ARCH_NIOS2
#endif

#ifdef EPP_TARGET_ARCH_OR1K
	#define EPP_CURRENT_ARCH	EPP_ARCH_OR1K
#endif

#ifdef EPP_TARGET_ARCH_PPC
	#define EPP_CURRENT_ARCH	EPP_ARCH_PPC
#endif

#ifdef EPP_TARGET_ARCH_PPC64
	#define EPP_CURRENT_ARCH	EPP_ARCH_PPC64
#endif

#ifdef EPP_TARGET_ARCH_RISCV32
	#define EPP_CURRENT_ARCH	EPP_ARCH_RISCV32
#endif

#ifdef EPP_TARGET_ARCH_RISCV64
	#define EPP_CURRENT_ARCH	EPP_ARCH_RISCV64
#endif

#ifdef EPP_TARGET_ARCH_RX
	#define EPP_CURRENT_ARCH	EPP_ARCH_RX
#endif

#ifdef EPP_TARGET_ARCH_S390X
	#define EPP_CURRENT_ARCH	EPP_ARCH_S390X
#endif

#ifdef EPP_TARGET_ARCH_SH4
	#define EPP_CURRENT_ARCH	EPP_ARCH_SH4
#endif

#ifdef EPP_TARGET_ARCH_SH4EB
	#define EPP_CURRENT_ARCH	EPP_ARCH_SH4EB
#endif

#ifdef EPP_TARGET_ARCH_SPARC
	#define EPP_CURRENT_ARCH	EPP_ARCH_SPARC
#endif

#ifdef EPP_TARGET_ARCH_SPARC64
	#define EPP_CURRENT_ARCH	EPP_ARCH_SPARC64
#endif

#ifdef EPP_TARGET_ARCH_TRICORE
	#define EPP_CURRENT_ARCH	EPP_ARCH_TRICORE
#endif

#ifdef EPP_TARGET_ARCH_X86_64
	#define EPP_CURRENT_ARCH	EPP_ARCH_X86_64
#endif

#ifdef EPP_TARGET_ARCH_XTENSA
	#define EPP_CURRENT_ARCH	EPP_ARCH_XTENSA
#endif

#ifdef EPP_TARGET_ARCH_XTENSAEB
	#define EPP_CURRENT_ARCH	EPP_ARCH_XTENSAEB
#endif


// 系统相关宏
#define EPP_OS_LINUX			0
#define EPP_OS_WINDOWS			1
#define EPP_OS_MACOS			2
#define EPP_OS_ANDROID			3
#define EPP_OS_IOS				4

// 宏转换
#ifdef EPP_TARGET_OS_LINUX
	#define EPP_CURRENT_OS		EPP_OS_LINUX
#endif

#ifdef EPP_TARGET_OS_WINDOWS
	#define EPP_CURRENT_OS		EPP_OS_WINDOWS
#endif

#ifdef EPP_TARGET_OS_MACOS
	#define EPP_CURRENT_OS		EPP_OS_MACOS
#endif

#ifdef EPP_TARGET_OS_IOS
	#define EPP_CURRENT_OS		EPP_OS_IOS
#endif

#ifdef EPP_TARGET_OS_ANDROID
	#define EPP_CURRENT_OS		EPP_OS_ANDROID
#endif

// 模块相关宏

// SDL2模块
#ifdef EPP_USE_SDL2_SUPPORT
	#define EPP_MODULE_SDL2_SUPPORT		EPP_TRUE
#else
	#define EPP_MODULE_SDL2_SUPPORT		EPP_FALSE
#endif

// X11模块
#ifdef EPP_USE_X11_SUPPORT
	#define EPP_MODULE_X11_SUPPORT		EPP_TRUE
#else
	#define EPP_MODULE_X11_SUPPORT		EPP_FALSE
#endif

